spring:
  config:
    activate:
      on-profile: dev

  # H2 Database Configuration
  datasource:
    driverClassName: org.h2.Driver
    url: ${DB_H2_URL}:${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.springframework: INFO
    com.example.demo: DEBUG
