spring:
  config:
    activate:
      on-profile: prod

  # MySQL Database Configuration
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework: INFO
    com.example.demo: DEBUG
